cities = [
    "Moscow", "Istanbul", "London", "Saint Petersburg", "Berlin",
    "Madrid", "Kiev", "Rome", "Paris", "Bucharest",
    "Budapest", "Warsaw", "Vienna", "Barcelona", "Kharkiv",
    "Munich", "Milan", "Prague", "Sofia", "Brussels",
    "Birmingham", "Cologne", "Naples", "Stockholm", "Amsterdam",
    "Zagreb", "Frankfurt", "Marseille", "Belgrade", "Oslo",
    "Copenhagen", "Helsinki", "Dublin", "Rotterdam", "Lisbon",
    "Manchester", "Athens", "Hamburg", "Vilnius",
    "Zurich", "Lyon", "Riga",
    "Stuttgart", "Glasgow", "Porto",
    "Poznan", "Seville", "Geneva", "Valencia",
    "Krakow", "Leipzig", "Palermo", "Bristol", "Turin",
    "Bremen", "Bratislava", "Katowice", "Antwerp", "The Hague",
    "Utrecht", "Thessaloniki", "Tallinn", "Dresden", "Bologna",
    "Genoa", "Gothenburg", "Sheffield", "Hanover", "Nuremberg",
    "Szczecin", "Bydgoszcz",
    "Mannheim", "Ostrava", "Timisoara", "Ljubljana",
    "Bochum", "Wuppertal", "Murcia", "Valladolid", "Wroclaw",
    "Aarhus", "Varna", "Gdansk",
    "Constanta", "Brno", "Florence",
    "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck",
    "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn",
    "Steyr", "Wiener Neustadt", "Feldkirch", "Bregenz", "Wolfsberg",
    "Baden", "Klosterneuburg", "Leoben", "Krems", "Traun",
    "Amstetten", "Lustenau", "Kapfenberg", "Mödling", "Hallein",
    "Kufstein", "Hohenems", "Bludenz", "Wörgl", "Eisenstadt",
    "Leonding", "Gmunden", "Tulln", "Braunau am Inn", "Ansfelden",
    "Stockerau", "Telfs", "Feldkirchen in Kärnten", "Bad Ischl", "Schwaz",
    "Hall in Tirol", "Bruck an der Mur", "Ternitz", "Korneuburg",
    "Rankweil", "Knittelfeld", "Perchtoldsdorf", "Traiskirchen", "Trofaiach",
    "Mistelbach"
]
